### ISSUE TITLE
target_env 不为 dev 时，APPCTL_ENV=dev 未被覆盖掉，导致 isDev 为 true

### ISSUE THREAD

**Issue by MrYourM** [QingCloudAppcenter/ansible-roles#30]
```
- name: set up dev env
  copy:
    dest: /opt/app/current/bin/envs/appdev.env
    content: |+
      APPCTL_ENV=dev
  when: target_env == 'dev'
```
